# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = {"vm.swappiness" = 10;};

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a5a64215-1605-485d-9bc9-635532a48d1e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fe106beb-b3f5-48e8-bceb-db276787edfa".device = "/dev/disk/by-uuid/fe106beb-b3f5-48e8-bceb-db276787edfa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/70E7-DF73";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/Media/Main" =
    { device = "/dev/disk/by-uuid/6f7939db-3392-4773-a4b2-8d7de563e8ef";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/04af2a33-e946-4d6d-9ad0-494b77ca8db6"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
